enum SEMANTIC_CONTAINER_TAGS {
   CONTAINER_LEADERBOARD = "main",
   CONTAINER_PRIMARY = "div",
   CONTAINER_ROW = "div"
}

enum SEMANTIC_TEXT_TAGS {
   HEADER_TEXT = "h2",
   SUB_HEADER_TEXT = "h3",
   PRIMARY_TEXT = "p",
   SECONDARY_TEXT = "p"
}

enum COMMON_STYLE_CLASS {
   ROOT_CONTAINER = "lb",
   HEADERS_CONTAINER = "lb_headers",
   COLUMN_CONTAINER = "lb_col",
   CONTAINER = "lb_container"
}

export const SEMANTIC_TAGS = { ...SEMANTIC_CONTAINER_TAGS, ...SEMANTIC_TEXT_TAGS };
export type SEMANTIC_TAGS = SEMANTIC_TEXT_TAGS | SEMANTIC_CONTAINER_TAGS;
export { SEMANTIC_CONTAINER_TAGS, SEMANTIC_TEXT_TAGS, COMMON_STYLE_CLASS };
