enum SEMANTIC_CONTAINER_TAGS {
   LEADERBOARD_ROOT = "main",
   CONTAINER_PRIMARY = "div"
}

enum COMPONENT_TYPES {
   CONTAINER = "container",
   TYPOGRAPHY = "typography",
   ROW = "row"
}

export { SEMANTIC_CONTAINER_TAGS, COMPONENT_TYPES };
