import { SEMANTIC_TEXT_TAGS } from "./semanticTextTags.enum";

enum SEMANTIC_CONTAINER_TAGS {
   CONTAINER_LEADERBOARD = "main",
   CONTAINER_PRIMARY = "div",
   CONTAINER_ROW = "div"
}

export const SEMANTIC_TAGS = { ...SEMANTIC_CONTAINER_TAGS, ...SEMANTIC_TEXT_TAGS };
export type SEMANTIC_TAGS = SEMANTIC_TEXT_TAGS | SEMANTIC_CONTAINER_TAGS;
